# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e369ddd42e5a71d22d442491e2f6c39e0a18c345aaeecbf278753b9882a6e441f27286b3d96928a34a6ca95a41c61ee13bd94aba09263d47b18d3130c5dc12d1
  two_factor_encryption_key: 134198f8f136e248bd77981d11d12f6d45a789181ba1997dbb22bf51903e29f4d4e9c3a2884c3ebb5cd253c1ea0fc79eae8468ca4d52a3d5c73a021b199146cf

test:
  secret_key_base: b63c8d6161483054ffa640145c90dc670f65b62d11f13e7b8f0d8dcb1d36ca5f619e48dfba3a25e60f1fed7824f7457d190954cc2531eef97b0152ec11425834

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
